---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "job.fullname" . }}
  labels: {{- include "job.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.config }}
      checksum/config: {{ toYaml . | sha256sum }}
    {{- end }}
    {{- with .Values.secrets }}
      checksum/secrets: {{ toYaml . | sha256sum }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}

  template:
    spec:
      restartPolicy: {{ .Values.restartPolicy }}

      {{- with .Values.image.pullSecretNames }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ include "job.fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- with .Values.command }}
          command: {{- toYaml .| nindent 12 }}
          {{- end }}

          {{- with .Values.config }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          {{- if .Values.secrets }}
          envFrom:
            - secretRef:
                name: {{ include "job.fullname" . }}
          {{- end }}

          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 16 }}
          {{- end }}
