{{- if .Values.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "job.fullname" . }}
  labels: {{- include "job.labels" . | nindent 4 }}
spec:
  encryptedData: {{- toYaml .Values.secrets | nindent 4 }}
{{ end }}
