---
# image is the configuration of image management
image:
  repository: vibioh/scratch
  pullPolicy: Always
  pullSecretNames:
    - dockerhub

# init container of the deployment, if any
init:
  enabled: false

  # configuration of init_container image management
  repository: vibioh/scratch
  pullPolicy: Always

  # command to run inside init_container
  command:
    - /bin/bash
    - "-c"
    - "echo Hello"

  # env variables passed to the pod
  env: {}

  # secrets map, in the form of a Sealed Secrets, created and passed to the init_container as a ref
  secrets: {}

  # resources requests and limits for defining the QoS
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi

# port HTTP listened
port: 1080

# livenessProbePath is the path of liveness
livenessProbePath: /health

# readinessProbePath is the path of readiness
readinessProbePath: /health

# config map created and passed to the pod as a ref
config: {}

# secrets map, in the form of a Sealed Secrets, created and passed to the pod as a ref
secrets: {}

# volumes array for deployment
volumes: []

# volumeMounts array for main container
volumeMounts: []

# strategy defines the rollout strategy for deployment
strategy: {}

# affinity for the deployment
affinity: {}

# securityContext for the main container
securityContext: {}

# resources requests and limits for defining the QoS
resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 200m
    memory: 64Mi

# service configuration for the service
service:
  type: ClusterIP
  port: 80

# prometheus enable prometheus scraping
prometheus: true

# ingress configuration of the Traefik's ingress, if any
ingress:
  enabled: false
  clusterIssuer: letsencrypt
  hosts:
    - example.localhost
  http_middlewares:
    - redirect@file
  https_middlewares:
    - compress@file
    - rate-limit@file
  # redirect:
  #   regex: ^https?://www.example.localhost(.*)
  #   replacement: https://example.localhost${1}

# pod_disruption configuration for the pod_disruption_budget, if any
pod_disruption:
  enabled: true
  minAvailable: 1

# autoscaling configuration for the horizontal pod autoscaler, if any
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetAverageUtilization: 75
