---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}

  jobTemplate:
    metadata:
      annotations:
      {{- with .Values.config }}
        checksum/config: {{ toYaml . | sha256sum }}
      {{- end }}
      {{- with .Values.secrets }}
        checksum/secrets: {{ toYaml . | sha256sum }}
      {{- end }}

    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          restartPolicy: {{ .Values.restartPolicy }}

          {{- with .Values.image.pullSecretNames }}
          imagePullSecrets:
            {{- range . }}
            - name: {{ . }}
            {{- end }}
          {{- end }}

          containers:
            {{- $root := . }}
            {{- range $root.Values.containers }}
            - name: {{ .name }}
              image: "{{ $root.Values.image.repository }}"
              imagePullPolicy: {{ $root.Values.image.pullPolicy }}

              {{- if len .args }}
              args:
                {{- toYaml .args | nindent 16 }}
              {{- end }}

              {{- if or $root.Values.config $root.Values.secrets }}
              envFrom:
              {{- if $root.Values.config }}
                - configMapRef:
                    name: {{ include "app.fullname" $root }}
              {{- end }}
              {{- if $root.Values.secrets }}
                - secretRef:
                    name: {{ include "app.fullname" $root }}
              {{- end }}
              {{- end }}

              {{- with $root.Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            {{- end }}
