---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}

  jobTemplate:
    metadata:
      annotations:
      {{- with .Values.config }}
        checksum/config: {{ toYaml . | sha256sum }}
      {{- end }}
      {{- with .Values.secrets }}
        checksum/secrets: {{ toYaml . | sha256sum }}
      {{- end }}

    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          restartPolicy: {{ .Values.restartPolicy }}

          {{- with .Values.image.pullSecretNames }}
          imagePullSecrets:
            {{- range . }}
            - name: {{ . }}
            {{- end }}
          {{- end }}

          containers:
            {{- range $.Values.containers }}
            - name: {{ .name }}
              image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}

              {{- with .command }}
              command: {{- toYaml . | nindent 16 }}
              {{- end }}

              {{- with .args }}
              args: {{- toYaml . | nindent 16 }}
              {{- end }}

              {{- if or $.Values.config $.Values.secrets }}
              envFrom:
              {{- if $.Values.config }}
                - configMapRef:
                    name: {{ include "app.fullname" $ }}
              {{- end }}
              {{- if $.Values.secrets }}
                - secretRef:
                    name: {{ include "app.fullname" $ }}
              {{- end }}
              {{- end }}

              {{- with $.Values.resources }}
              resources: {{- toYaml . | nindent 16 }}
              {{- end }}
            {{- end }}
