---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      annotations:
      {{- with .Values.config }}
        checksum/config: {{ toYaml . | sha256sum }}
      {{- end }}
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
            {{- $root := . }}
            {{- range $root.Values.containers }}
            - name: {{ .name }}
              image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag | default $root.Chart.AppVersion }}"
              imagePullPolicy: {{ $root.Values.image.pullPolicy }}
              {{- if len .args }}
              args: {{ .args }}
              {{- end }}
              {{- if or $root.Values.config $root.Values.secretRef }}
              envFrom:
              {{- if $root.Values.config }}
                - configMapRef:
                    name: {{ include "app.fullname" $root }}
              {{- end }}
              {{- if $root.Values.secretRef }}
                - secretRef:
                    name: {{ $root.Values.secretRef }}
              {{- end }}
              {{- end }}
              {{- with $root.Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            {{- end }}
