{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
data: {{- toYaml .Values.config | nindent 2 }}
{{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-init
  labels: {{- include "app.labels" . | nindent 4 }}
data:
  databases.sh: |
    #!/usr/bin/env bash

    set -o nounset -o pipefail -o errexit
{{ range .Values.databases }}
    psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
      CREATE USER {{ .user }} WITH ENCRYPTED PASSWORD '${{ .password }}';
      CREATE DATABASE {{ .name }};
      GRANT ALL PRIVILEGES ON DATABASE {{ .name }} TO {{ .user }};
    EOSQL
{{- end }}
