{{- if .Values.backup.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-backup
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.backup.concurrencyPolicy }}
  schedule: {{ .Values.backup.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.backup.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backup.failedJobsHistoryLimit }}

  jobTemplate:
    metadata:
      annotations:
      {{- with .Values.config }}
        checksum/config: {{ toYaml . | sha256sum }}
      {{- end }}
      {{- with .Values.secrets }}
        checksum/secrets: {{ toYaml . | sha256sum }}
      {{- end }}

    spec:
      backoffLimit: {{ .Values.backup.backoffLimit }}
      template:
        spec:
          restartPolicy: {{ .Values.backup.restartPolicy }}
          containers:
            - name: {{ include "app.fullname" . }}-backup
              image: "{{ .Values.image.repository }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}

              command: 
                - /bin/bash
                - -c
                - |
                  export PGPASSWORD="${POSTGRES_PASSWORD}"; export BACKUP_FILENAME="${POSTGRES_DB}_backup_$(date -Iseconds)"; pg_dump --host={{ include "app.fullname" . }} --port={{ .Values.service.port }} --username="${POSTGRES_USER}" --format=c "${POSTGRES_DB}" --data-only > "${BACKUP_FILENAME}" && {{ .Values.backup.uploadCommand }}"${BACKUP_FILENAME}"

              {{- if or .Values.config .Values.secrets }}
              envFrom:
              {{- if .Values.config }}
                - configMapRef:
                    name: {{ include "app.fullname" . }}
              {{- end }}
              {{- if .Values.secrets }}
                - secretRef:
                    name: {{ include "app.fullname" . }}
              {{- end }}
              {{- end }}

              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
{{- end }}
