---
# image is the configuration of image management
image:
  repository: postgres
  tag: 12-alpine
  pullPolicy: Always

# podAnnotations placed on the pod
podAnnotations: {}

# config map created and passed to the pod as a ref
config:
  POSTGRES_USER: app
  POSTGRES_DB: app
  PGDATA: /var/lib/postgresql/data/pgdata

# post used by postgres
port: 5432

# persistentVolume for storing databases datas
persistentvolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  storage: 200Mi

# secrets map, in the form of a Sealed Secrets, created and passed to the pod as a ref
secrets:
  POSTGRES_PASSWORD: changeme

# strategy defines the rollout strategy for deployment
strategy: {}

# resources requests and limits for defining the QoS
resources:
  limits:
    cpu: 100m
    memory: 100M
  requests:
    cpu: 100m
    memory: 100M

# service configuration for the service
service:
  type: ClusterIP
  port: 80

# pod_disruption configuration for the pod_disruption_budget, if any
pod_disruption:
  enabled: true
  minAvailable: 1

# backup configure cronjob of backup
backup:
  enabled: true
  restartPolicy: Never
  concurrencyPolicy: Forbid
  schedule: "0 5 * * *"

  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  backoffLimit: 3

  httpUrl: https://fibr.vibioh.fr/20ace1a0/
  httpUser: app
  httpPasswordEnv: FIBR_BACKUP_PASSWORD
