{{- if .Values.image_automation }}

{{- range .Values.images }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: {{ include "app.fullname" $ }}-{{ .id }}
  labels: {{- include "app.labels" $ | nindent 4 }}
spec:
  interval: 6h
  timeout: 1m
  image: {{ .name }}
  {{- if .secret }}
  secretRef:
    name: {{ .secret }}
  {{- end }}

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: {{ include "app.fullname" $ }}-{{ .id }}
  labels: {{- include "app.labels" $ | nindent 4 }}
spec:
  imageRepositoryRef:
    name: {{ include "app.fullname" $ }}-{{ .id }}
  {{- if eq .policy "semver" }}
  policy:
    semver:
      range: ">=0.0.1"
  {{- else }}
  filterTags:
    pattern: ^[0-9]{12}
  policy:
    numerical:
      order: asc
  {{- end }}
{{- end }}

{{- if .Values.images }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: {{ include "app.fullname" . }}
  git:
    checkout:
      ref:
        branch: {{ .Values.repository.branch }}
    commit:
      messageTemplate: |
        ci(flux): [skip ci] Automated image update for {{ `{{ .AutomationObject }}` }}

        Images:
        {{ `{{- range .Updated.Images }}
        - {{.}}
        {{- end }}` }}
      author:
        name: Flux
        email: flux@vibioh.fr
      signingKey:
        secretRef:
          name: github-ssh
  update:
    path: {{ .Values.repository.path }}
    strategy: Setters

---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: {{ include "app.fullname" . }}-image
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  type: generic-hmac
  secretRef:
    name: {{ .Values.receiver.token }}
  resources:
    {{- range .Values.images }}
    - kind: ImageRepository
      name: {{ include "app.fullname" $ }}-{{ .id }}
    {{- end }}
{{- end }}

{{- end }}
