{{- $root := . -}}

{{- range .Values.images }}
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: {{ include "app.fullname" $root }}-{{ .id }}
  labels: {{- include "app.labels" $root | nindent 4 }}
spec:
  interval: 60m
  image: {{ .name }}

---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: {{ include "app.fullname" $root }}-{{ .id }}
  labels: {{- include "app.labels" $root | nindent 4 }}
spec:
  imageRepositoryRef:
    name: {{ include "app.fullname" $root }}-{{ .id }}
  filterTags:
    pattern: ^[0-9]{12}
  policy:
    numerical:
      order: asc
{{- end }}

{{- if .Values.images }}
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: {{ include "app.fullname" . }}
  git:
    checkout:
      ref:
        branch: {{ .Values.repository.branch }}
    commit:
      messageTemplate: "ci(flux): [skip ci] Update image from automation"
      author:
        name: Flux
        email: flux@vibioh.fr
  update:
    strategy: Setters

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: {{ include "app.fullname" . }}-image
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  type: generic-hmac
  secretRef:
    name: {{ .Values.receiver.token }}
  resources:
    {{- range .Values.images }}
    - kind: ImageRepository
      name: {{ include "app.fullname" $root }}-{{ .id }}
    {{- end }}
{{- end }}
