---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  interval: 6h
  ref:
    branch: {{ .Values.repository.branch }}
  url: ssh://git@{{ .Values.repository.type }}.com/{{ .Values.repository.name }}
  secretRef:
    name: {{ .Values.repository.secret }}

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  interval: 6h
  path: {{ .Values.repository.path }}
  prune: {{ .Values.prune }}
  sourceRef:
    kind: GitRepository
    name: {{ include "app.fullname" . }}
