---
# image configuration
image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "6.2-alpine"

# imagePullSecrets for pulling image, array of strings
imagePullSecrets:
  - dockerhub

# podAnnotations placed on the pod
podAnnotations: {}

# port used by redis
port: 6379

# user used by redis
user: 1000

# secrets content, as a SealedSecret, mounted into "/usr/local/etc/redis"
secrets:
  redis.conf: ""
  REDIS_PASSWORD: ""

# strategy defines the rollout strategy for deployment
strategy:
  type: Recreate

# persistentVolume for storing databases datas
persistentvolume:
  enabled: false
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  storage: 200Mi

# resources requests and limits for defining the QoS
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi

# service configuration for the service
service:
  type: ClusterIP
  port: 80

prometheus:
  enabled: true
  port: 9090
  path: /metrics
  image:
    repository: oliver006/redis_exporter
    pullPolicy: IfNotPresent
    tag: v1.35.1
