---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}

  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}

  template:
    metadata:
      annotations:
      {{- with .Values.prometheus }}
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
        prometheus.io/port: "{{ .port }}"
      {{- end }}
      {{- with .Values.config }}
        checksum/config: {{ toYaml . | sha256sum }}
      {{- end }}
      {{- with .Values.secrets }}
        checksum/secrets: {{ toYaml . | sha256sum }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.image.pullSecretNames }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ include "app.fullname" . }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if or .Values.config .Values.secrets }}
          envFrom:
          {{- if .Values.config }}
            - configMapRef:
                name: {{ include "app.fullname" . }}
          {{- end }}
          {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "app.fullname" . }}
          {{- end }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP

          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.livenessProbePath }}
          livenessProbe:
            httpGet:
              path: {{ . | quote }}
              port: http
          {{- end }}
          {{- with .Values.readinessProbePath }}
          readinessProbe:
            httpGet:
              path: {{ . | quote }}
              port: http
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- if .Values.init.enabled }}
      initContainers:
        - name: {{ include "app.fullname" . }}-init
          image: "{{ .Values.init.repository }}"
          imagePullPolicy: {{ .Values.init.pullPolicy }}
          {{- with .Values.init.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.init.secrets }}
          envFrom:
            - secretRef:
                name: {{ include "app.fullname" . }}-init
          {{- end }}
          {{- if .Values.init.command }}
          command:
            {{- toYaml .Values.init.command | nindent 12 }}
          {{- end }}
          {{- if .Values.init.resources }}
          resources:
            {{- toYaml .Values.init.resources | nindent 12 }}
          {{- end }}
      {{- end }}
