---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.config }}
        checksum/config: {{ toYaml . | sha256sum }}
      {{- end }}
      {{- with .Values.secrets }}
        checksum/secrets: {{ toYaml . | sha256sum }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "app.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.config .Values.secrets }}
          envFrom:
          {{- if .Values.config }}
            - configMapRef:
                name: {{ include "app.fullname" . }}
          {{- end }}
          {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "app.fullname" . }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbePath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbePath  }}
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.init.enabled }}
      initContainers:
        - name: {{ include "app.fullname" . }}-init
          image: "{{ .Values.init.repository }}:{{ .Values.init.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.init.pullPolicy }}
          {{- with .Values.init.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.init.secrets }}
          envFrom:
            - secretRef:
                name: {{ include "app.fullname" . }}-init
          {{- end }}
          {{- if .Values.init.command }}
          command:
            {{- toYaml .Values.init.command | nindent 12 }}
          {{- end }}
          {{- if .Values.init.resources }}
          resources:
            {{- toYaml .Values.init.resources | nindent 12 }}
          {{- end }}
      {{- end }}
