{{- if .Values.ingress.enabled -}}

{{- $customMiddlewares := list -}}

{{- if .Values.ingress.redirect }}
  {{- $redirectMiddleware := printf "%s-%s" (include "app.fullname" .) "redirect" -}}
  {{- $customMiddlewares = append $customMiddlewares $redirectMiddleware -}}
{{- end -}}

{{- if .Values.ingress.rateLimit -}}
  {{- $customMiddlewares = append $customMiddlewares "ratelimit@file" -}}
{{- end -}}

{{- if .Values.ingress.compress -}}
  {{- $customMiddlewares = append $customMiddlewares "compress@file" -}}
{{- end -}}

{{- $httpMiddlewares := concat $customMiddlewares .Values.ingress.http_middlewares -}}
{{- $httpsMiddlewares := concat $customMiddlewares .Values.ingress.https_middlewares -}}

{{- if .Values.ingress.httpsUpgrade -}}
  {{- $httpMiddlewares = append $customMiddlewares "redirect@file" -}}
{{- end -}}

{{- if .Values.ingress.redirect }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.fullname" . }}-redirect
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  redirectRegex:
    regex: {{ .Values.ingress.redirect.regex }}
    replacement: {{ .Values.ingress.redirect.replacement }}
{{- end }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  secretName: {{ include "app.fullname" . }}-tls
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ . }}
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.ingress.clusterIssuer }}
    group: cert-manager.io

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app.fullname" . }}-http
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ . }}`)
      kind: Rule
      {{- with $httpMiddlewares }}
      middlewares:
        {{- range . }}
        - name: {{ . }}
          {{- if not (contains "@" .) }}
          namespace: {{ $.Release.Namespace }}
          {{- end}}
        {{- end }}
      {{- end }}
      services:
        - name: {{ include "app.fullname" $ }}
          port: {{ $.Values.service.port }}
          {{- if $.Values.canary.enabled }}
          kind: TraefikService
          {{- end }}
    {{- end }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app.fullname" . }}-https
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ include "app.fullname" . }}-tls
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ . }}`)
      kind: Rule
      {{- with $httpsMiddlewares }}
      middlewares:
        {{- range . }}
        - name: {{ . }}
          {{- if not (contains "@" .) }}
          namespace: {{ $.Release.Namespace }}
          {{- end}}
        {{- end }}
      {{- end }}
      services:
        - name: {{ include "app.fullname" $ }}
          port: {{ $.Values.service.port }}
          {{- if $.Values.canary.enabled }}
          kind: TraefikService
          {{- end }}
          {{- if $.Values.ingress.sticky }}
          sticky:
            cookie:
              httpOnly: true
              name: sticky
              secure: true
              sameSite: strict
          {{- end }}
    {{- end }}
{{- end -}}
