{{- if .Values.ingress.enabled -}}

{{- $root := . -}}

{{- $redirectMiddlewares := list -}}
{{- if .Values.ingress.redirect }}
  {{- $redirectMiddleware := printf "%s-%s-%s" .Release.Namespace (include "app.fullname" $root) "redirect@kubernetescrd" -}}
  {{- $redirectMiddlewares = append $redirectMiddlewares $redirectMiddleware -}}
{{- end -}}

{{- $httpMiddlewares := concat $redirectMiddlewares .Values.ingress.http_middlewares -}}
{{- $httpsMiddlewares := concat $redirectMiddlewares .Values.ingress.https_middlewares -}}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-http
  annotations:
    {{- with $httpMiddlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "app.joinComma" . }}
    {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: "{{ . }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" $root }}
                port:
                  number: {{ $root.Values.service.port }}
    {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-https
  annotations:
    {{- with $httpsMiddlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "app.joinComma" . }}
    {{- end }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: "{{ . }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" $root }}
                port:
                  number: {{ $root.Values.service.port }}
    {{- end }}
{{- end -}}
