{{- if .Values.ingress.enabled -}}

{{- $root := . -}}
{{- $httpMiddlewares := .Values.ingress.http_middlewares -}}
{{- if .Values.ingress.redirect }}
  {{- $redirectMiddleware := printf "%s-%s" (include "app.fullname" $root) "redirect" -}}
  {{- $httpMiddlewares = append $httpMiddlewares $redirectMiddleware -}}
{{- end -}}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-http
  annotations:
    {{- with $httpMiddlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "app.joinComma" . }}
    {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: "{{ . }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" $root }}
                port:
                  number: {{ $root.Values.service.port }}
    {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-https
  annotations:
    {{- with .Values.ingress.https_middlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "app.joinComma" . }}
    {{- end }}
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: "{{ . }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" $root }}
                port:
                  number: {{ $root.Values.service.port }}
    {{- end }}
{{- end -}}
