{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app.fullname" . }}-http
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  entryPoints:
    - http
  routes:
    - match: {{ include "ingress.hosts" . }}
      kind: Rule
      middlewares:
        {{- range .Values.ingress.http_middlewares }}
        - name: {{ . }}
        {{- end }}
        {{- if .Values.redirect }}
        - name: {{ include "app.fullname" . }}-redirect
        {{- end }}
      services:
        - name: {{ include "app.fullname" . }}
          namespace: {{ .Values.namespace }}
          port: {{ .Values.service.port }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app.fullname" . }}-https
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  entryPoints:
    - https
  routes:
    - match: {{ include "ingress.hosts" . }}
      kind: Rule
      middlewares:
        {{- range .Values.ingress.https_middlewares }}
        - name: {{ . }}
        {{- end }}
        {{- if .Values.ingress.redirect }}
        - name: {{ include "app.fullname" . }}-redirect
        {{- end }}
      services:
        - name: {{ include "app.fullname" . }}
          namespace: {{ .Values.namespace }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: default
{{- end -}}
