{{- if .Values.ingress.enabled -}}

{{- $root := . -}}

{{- $customMiddlewares := list -}}
{{- if .Values.ingress.redirect }}
  {{- $redirectMiddleware := printf "%s-%s-%s" .Release.Namespace (include "app.fullname" .) "redirect@kubernetescrd" -}}
  {{- $customMiddlewares = append $customMiddlewares $redirectMiddleware -}}
{{- end -}}

{{- $httpMiddlewares := concat $customMiddlewares .Values.ingress.http_middlewares -}}
{{- $httpsMiddlewares := concat $customMiddlewares .Values.ingress.https_middlewares -}}

{{- if .Values.ingress.redirect }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.fullname" . }}-redirect
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  redirectRegex:
    regex: {{ .Values.ingress.redirect.regex }}
    replacement: {{ .Values.ingress.redirect.replacement }}
{{- end }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.fullname" . }}
spec:
  secretName: {{ include "app.fullname" . }}-tls
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ . }}
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
    group: cert-manager.io

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app.fullname" . }}-http
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  {{- with $httpMiddlewares }}
  middlewares:
    {{- range . }}
    - name: {{ . }}
    {{- end }}
  {{- end }}
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ . }}`)
      kind: Rule
      services:
        - name: {{ include "app.fullname" $root }}
          port: {{ $root.Values.service.port }}
    {{- end }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app.fullname" . }}-https
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  {{- with $httpsMiddlewares }}
  middlewares:
    {{- range . }}
    - name: {{ . }}
    {{- end }}
  {{- end }}
  tls:
    secretName: {{ include "app.fullname" . }}-tls
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ . }}`)
      kind: Rule
      services:
        - name: {{ include "app.fullname" $root }}
          port: {{ $root.Values.service.port }}
    {{- end }}
{{- end -}}
