{{- if and .Values.ingress.enabled .Values.ingress.redirect }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.fullname" . }}-redirect
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  redirectRegex:
    regex: {{ .Values.ingress.redirect.regex }}
    replacement: {{ .Values.ingress.redirect.replacement }}
{{- end }}
