{{- if .Values.sealed_secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.sealed_secrets | nindent 4 }}
{{ end }}
